[workspace]
members = [
    "crates/hyle",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.2.0"
license = "BSD-2-Clause"
repository = "https://github.com/tty-pt/hyle"

[workspace.dependencies]
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
hyle = { path = "crates/hyle", version = "0.2.0" }

[profile.dev]
opt-level = 2

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
